{{- define "replicaNumber" -}}
{{- if .Values.storageClass.enableHA -}}
{{- print 2 -}}
{{- else -}}
{{- print 1 -}}
{{- end -}}
{{- end -}}

{{- range $storageclass := .Values.storageClass -}}
---

{{- if $storageclass.enabled -}}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    storageclass.kubernetes.io/is-default-class: {{ $storageclass.default | quote }}
  name: hwameistor-storage-lvm-{{ $storageclass.diskType | lower}}
provisioner: lvm.hwameistor.io
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: {{ $storageclass.allowVolumeExpansion }}
reclaimPolicy: {{ $storageclass.reclaimPolicy }}
parameters:
  replicaNumber: {{ include "replicaNumber" . | quote}}
  poolClass: {{ $storageclass.diskType | quote}}
  poolType: "REGULAR"
  volumeKind: "LVM"
  striped: "true"
  convertible: {{ $storageclass.convertible | quote}}
  csi.storage.k8s.io/fstype: {{ $storageclass.fsType | quote}}
{{- end }}
{{ end }}